FROM microsoft/windowsservercore:1803
WORKDIR C:/Users/Administrator
# Specifying the user like this could, theoretically,
# fix some of the installation/menu problems 
# USER Administrator
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

RUN Invoke-WebRequest 'https://repo.continuum.io/miniconda/Miniconda3-latest-Windows-x86_64.exe' -OutFile 'Miniconda3.exe' -verbose
RUN Start-Process .\Miniconda3.exe -ArgumentList '/S','/InstallationType=AllUsers','/AddToPath=1','/RegisterPython=1' -Wait
RUN del Miniconda3.exe

RUN conda install --yes conda-build
COPY lmgc90_dev.zip C:/Users/Administrator/lmgc90_dev.zip
ADD conda/ C:/Users/Administrator/conda/

RUN conda build purge
RUN conda build . -c conda-forge
RUN conda install --use-local lmgc90 -c conda-forge
