
// Doxygen main page file

/*! \mainpage Doxygen documentation of LMGC90
  
  \section intro Introduction
 
  You are currently reading the documentation
  of LMGC90 automatically generated by Doxygen

  You will in this page some reminder about the
  existing documentation of LMGC90

  The other pages will give information on the
  code itself
 
  \section sec1 Reminders
 
  Reference web sites of LMGC90"s users :
  https://git-xen.lmgc.univ-montp2.fr/lmgc90/lmgc90_user/wikis/home

  Reference web sites of LMGC90"s developpers :
  https://git-xen.lmgc.univ-montp2.fr/lmgc90/lmgc90_dev/wikis/home
 
  These sites give reminders on how to download and build the software.

  Theoretical documentation and tutorial can be found in the "manuals" directory once
  the sources of the software is downloaded.

  To generate again this documentation in your build directory type :
  "make docs"
 

  \section sec2 What to find in this documentation

  The list of every module in the software is in the "Modules" thumbnail.
  The list of every file in the software is in the "Files" thumbnail.

  To get information on a module of the Core, look for its name
  in the "Modules" thumbnail.

  To get information on the Fortran API, look for the modules which
  name begins with "wrap_" in the "Modules" thumbnail.

  To get information on the C/C++ API, look for the files which name
  ends in .h in the "Files" thumbnail
 
*/

//  \page page1 A documentation page
//  Leading text.
//
//  What would be great : to remove this index.h file from the list of files !
//  And to sort out how to add proper carriage return in python docsctring generated
//
//  \section sec An example section
//  This page contains the subsections \ref subsection1 and \ref subsection2.
//  For more info see page \ref page2.
//  \subsection subsection1 The first subsection
//  Text.
//  \subsection subsection2 The second subsection
//  More text.

