# This is part of LMGC90-v0.0 by F.Dubois & M.Jean (c) 2001 CNRS-UMII 

CC=gcc
CFLAGS=
LIBS=libstandalone.a
LIBS_PATH=$(PWD)/..

c_stand:
	$(CC) $(CFLAGS) -o exe  $(LIBS_PATH)/$(LIBS) main.c 

clean:
	@rm -f exe
